<?php
/**
 * Created by PhpStorm.
 * User: Tioncico
 * Date: 2019/3/29 0029
 * Time: 10:45
 */

namespace App\HttpController\Api;


use App\HttpController\Base;
use App\Service\ServiceException;
use EasySwoole\Http\Message\Status;
use EasySwoole\Validate\Validate;

abstract class ApiBase extends Base
{
    function onRequest(?string $action): ?bool
    {
        if (!parent::onRequest($action)) {
            return false;
        };
        /*
         * 各个action的参数校验
         */
        $v = $this->getValidateRule($action);
        if ($v && !$this->validate($v)) {
            $this->writeJson(Status::CODE_BAD_REQUEST, ['errorCode' => 1, 'data' => []], $v->getError()->__toString());
            return false;
        }
        return true;
    }

//    abstract protected function getValidateRule(?string $action): ?Validate;

    function onException(\Throwable $throwable): void
    {
        if ($throwable instanceof ServiceException) {
            $this->writeJson(Status::CODE_BAD_REQUEST, ['errorCode' => 1, 'data' => []], $throwable->getMessage());
        } else {
            parent::onException($throwable); // TODO: Change the autogenerated stub
        }
    }
}